publish_mode: editorial_workflow

backend:
  name: github
  branch: main 
  repo: olavflar/baksia-cms-test

local_backend: true

  i18n:
  structure: multiple_files
  locales: [nb,en,nn]
  default_locale: nb
  
media_folder: static/img
public_folder: /img
collections:

